var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};
$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in d||(d[c]={});d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(h){this.asyncThrow_(h)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(h){c.reject(h)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(n){f(n)}}:b}var e,f,g=new c(function(a,b){e=a;f=b});this.callWhenSettled_(d(a,e),d(b,f));return g};
c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(c)};c.resolve=d;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,
c)})};c.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?d([]):new c(function(a,c){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,d(e.value).callWhenSettled_(f(g.length-1),c),e=b.next();while(!e.done)})};return c},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+b++,d)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var d=a.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var c=e.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(e,c){function f(a){a.done?e(a.value):Promise.resolve(a.value).then(b,d).then(f,c)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),cw=canvas.width,ch=canvas.height;function reOffset(){var a=canvas.getBoundingClientRect();offsetX=a.left;offsetY=a.top;cw=canvas.width;ch=canvas.height}var offsetX,offsetY;reOffset();window.onscroll=function(a){reOffset()};window.onresize=function(a){reOffset()};var pressed=-1,score=0,images=[],gw=4,gh=4,phase,anim_frames=5,anim_length=30,anim_phase,anim,spawn,state,gameover,last=1;
function spawnRand(a){clearAnim();0===a&&(a=.5>Math.random()?1:2);var b=emptyCells(),d=b.splice(Math.floor(Math.random()*b.length),1)[0];state[d[0]][d[1]]=a;spawn[d[0]][d[1]]=1;0===b.length&&(!1===gameover&&playSound(38733900),gameover=!0)}function clearCell(a,b){var d=state[a][b];if(0===d)return!1;spawn[a][b]=-d;state[a][b]=0;return!0}
function resetGame(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){switch(a.nextAddress){case 1:playSound(90509500),gameover=!1,anim=[[[0,0],[0,0],[0,0],[0,0],[0,0]],[[0,0],[0,0],[0,0],[0,0],[0,0]],[[0,0],[0,0],[0,0],[0,0],[0,0]],[[0,0],[0,0],[0,0],[0,0],[0,0]],[[0,0],[0,0],[0,0],[0,0],[0,0]]],state=[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]],spawn=[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]],score=phase=anim_phase=0,spawnRand(1),anim_phase=0;case 2:if(!(2>
anim_phase)){a.jumpTo(4);break}redraw();return a.yield(sleep(30),3);case 3:anim_phase++;a.jumpTo(2);break;case 4:clearAnim(),redraw(),spawnRand(2),anim_phase=0;case 6:if(!(2>anim_phase)){a.jumpTo(8);break}redraw();return a.yield(sleep(30),7);case 7:anim_phase++;a.jumpTo(6);break;case 8:return clearAnim(),redraw(),a.return(Promise.resolve(1))}})}function unpress(){pressed=-1;-1===phase&&(phase=0);redraw()}
function animtick(){anim_phase++;anim_phase>anim_frames&&(anim_phase=anim_frames);anim_phase<anim_frames?setTimeout(animtick,anim_length):phase=0;redraw()}var piece_frames={1:["weiss","weiss_1","weiss_1","weiss_1"],2:["schwarz","schwarz_1","schwarz_1","weiss_1"]};
function redraw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(images.geraet2,0,0);for(var a=score.toString();3>a.length;)a="0"+a;for(var b=0;3>b;b++)ctx.drawImage(images[a[b]],54+4*b,10);ctx.fillStyle="#00FF00";for(b=0;b<phase;b++)ctx.fillRect(55+4*b,52,1,1);-1===phase&&(ctx.fillStyle="#FF0000",ctx.fillRect(55+4*b,52,1,1));if(gameover)for(ctx.fillStyle="#FF0000",b=0;4>b;b++)ctx.fillRect(55+4*b,52,1,1);for(b=0;b<gw;b++)for(a=0;a<gh;a++){var d=Math.floor(8*anim[b][a][0]*(1-anim_phase/
anim_frames)),e=Math.floor(8*anim[b][a][1]*(1-anim_phase/anim_frames)),c=0,f=state[b][a];1===spawn[b][a]&&(c=2-anim_phase);-1===spawn[b][a]&&(f=c=1);-2===spawn[b][a]&&(c=1,f=2);1===f?ctx.drawImage(images[piece_frames[f][c]],19+8*b+d,19+8*a+e):2===f&&ctx.drawImage(images[piece_frames[f][c]],19+8*b+d,19+8*a+e)}0<=pressed&&(b=image_x_y[pressed],ctx.drawImage(images[b[0]],b[1],b[2]),setTimeout(unpress,200))}
for(var image_names="geraet2 b_up_sm b_down_sm b_left_sm b_right_sm reset 0 1 2 3 4 5 6 7 8 9 schwarz weiss weiss_1 weiss_0 schwarz_1 schwarz_0".split(" "),image_x_y=[["b_up_sm",19,8,31,8],["b_down_sm",19,53,31,8],["b_left_sm",8,19,8,31],["b_right_sm",53,19,8,31],["reset",60,55,6,6]],i=0;i<image_names.length;i++){var image=new Image;image.onload=function(){redraw()};image.src=image_names[i]+".png";images[image_names[i]]=image}
function trypush(a,b){for(var d=!1,e=0;e<gw;e++)for(var c=0;c<gh;c++)if(0!==state[e][c]){var f=e+a,g=c+b;0>f||f>=gw||0>g||g>=gh||0!==state[f][g]||(state[f][g]=state[e][c],state[e][c]=0,anim[f][g][0]=anim[e][c][0]-a,anim[f][g][1]=anim[e][c][1]-b,anim[e][c][0]=0,anim[e][c][1]=0,d=!0)}return d}function sleep(a){return new Promise(function(b){return setTimeout(b,a)})}function clearAnim(){for(var a=0;a<gw;a++)for(var b=0;b<gh;b++)anim[a][b][0]=0,anim[a][b][1]=0,spawn[a][b]=0}
function full(){for(var a=0;a<gw;a++)for(var b=0;b<gh;b++)if(0===state[a][b])return!0;return!1}var moving=!1;
function doMove(a,b){var d,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){switch(c.nextAddress){case 1:d=!1;clearAnim();for(e=!0;e;)e=!1,trypush(a,b)&&(d=e=!0);if(!1!==d){c.jumpTo(2);break}anim_phase=-1;redraw();return c.yield(sleep(30),3);case 3:return phase=anim_phase=1,redraw(),c.return(Promise.resolve(1));case 2:playSound(11309707),anim_phase=phase=1;case 4:if(!(anim_phase<anim_frames)){phase=2;clearAnim();if(!tryClear()){c.jumpTo(8);break}playSound(53413900);return c.yield(sleep(30),
9)}redraw();return c.yield(sleep(30),5);case 5:anim_phase++;c.jumpTo(4);break;case 9:anim_phase=0;case 10:if(!(2>anim_phase))return clearAnim(),redraw(),c.yield(sleep(30),8);redraw();return c.yield(sleep(30),11);case 11:anim_phase++;c.jumpTo(10);break;case 8:phase=3,spawnRand(0),anim_phase=0;case 15:if(!(2>anim_phase)){clearAnim();redraw();phase=4;clearAnim();if(!tryClear()){c.jumpTo(19);break}playSound(53413900);return c.yield(sleep(30),20)}redraw();return c.yield(sleep(30),16);case 16:anim_phase++;
c.jumpTo(15);break;case 20:anim_phase=0;case 21:if(!(2>anim_phase)){c.jumpTo(23);break}redraw();return c.yield(sleep(30),22);case 22:anim_phase++;c.jumpTo(21);break;case 23:clearAnim(),redraw();case 19:return phase=0,redraw(),c.return(Promise.resolve(1))}})}
function doPress(a){return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress){if(!0===moving)return b.return();moving=!0;pressed=a;return 0===a?b.yield(doMove(0,-1),3):1===a?b.yield(doMove(0,1),3):2===a?b.yield(doMove(-1,0),3):3===a?b.yield(doMove(1,0),3):4!==a?b.jumpTo(3):b.yield(resetGame(),3)}moving=!1;b.jumpToEnd()})}
function getMousePos(a){var b=canvas.getBoundingClientRect(),d=canvas.width/b.width,e=canvas.height/b.height,c=a.clientX;a=a.clientY;d<e?(d=e,c-=b.width/2-cw/d/2):(e=d,a-=b.height/2-ch/e/2);return[(c-b.left)*d,(a-b.top)*e]}
function handleTap(a){var b=$jscomp.makeIterator(getMousePos(a)),d=b.next().value;b=b.next().value;console.log(a);console.log(d+","+b);ctx.getImageData(d,b,1,1);for(a=0;a<image_x_y.length;a++){var e=image_x_y[a],c=e[1],f=e[2],g=e[1]+e[3];e=e[2]+e[4];d>=c&&d<=g&&b>=f&&b<=e&&(console.log("("+d+","+b+")~["+c+","+f+","+g+","+e+"]"),doPress(a))}}function emptyCells(){for(var a=[],b=0;b<gw;b++)for(var d=0;d<gh;d++)0===state[b][d]&&a.push([b,d]);return a}
function neighbors(a,b){var d=[];0<a&&d.push([a-1,b]);a<gw-1&&d.push([a+1,b]);0<b&&d.push([a,b-1]);b<gh-1&&d.push([a,b+1]);return d}
function versuchFloodFill(a,b,d){if(0===state[a][b])return!1;var e=state[a][b];console.log("farbe "+e);a+=gw*b;if(0<=d.indexOf(a))return!1;console.log("not already present");a=[a];for(b=!0;b;){b=!1;for(var c=0;c<gw;c++)for(var f=0;f<gh;f++){var g=c+gw*f;if(!(0<=a.indexOf(g))){for(var l=!1,k=neighbors(c,f),h=0;h<k.length;h++){var m=k[h];0<=a.indexOf(m[0]+gw*m[1])&&(l=!0)}if(!1!==l){l=state[c][f];if(0==l)return!1;l===e&&(a.push(g),b=!0)}}}}16===a.length&&(a=[]);for(c=0;c<a.length;c++)d.push(a[c]);return 0<
a.length}function tryClear(){if(0===emptyCells().length)return!1===gameover&&playSound(38733900),gameover=!0,!1;console.log("tryclear");for(var a=[],b=0;b<gw;b++)for(var d=0;d<gh;d++)0!=state[b][d]&&versuchFloodFill(b,d,a)&&score++;for(b=0;b<a.length;b++)d=a[b],clearCell(d%gw,Math.floor(d/gw));return 0<a.length}
function handleKey(a){if("ArrowUp"===a.key)return doPress(0),a.preventDefault(),!1;if("ArrowDown"===a.key)return doPress(1),a.preventDefault(),!1;if("ArrowLeft"===a.key)return doPress(2),a.preventDefault(),!1;if("ArrowRight"===a.key)return doPress(3),a.preventDefault(),!1;if("r"===a.key.toLowerCase()||"n"===a.key.toLowerCase())return doPress(4),a.preventDefault(),!1}canvas.addEventListener("pointerdown",handleTap);document.addEventListener("keydown",handleKey);resetGame();
