/*
 PEP v0.4.3 | https://github.com/jquery/PEP
 Copyright jQuery Foundation and other contributors | http://jquery.org/license
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.checkEs6ConformanceViaProxy=function(){try{var b={},e=Object.create(new $jscomp.global.Proxy(b,{get:function(k,h,m){return k==b&&"q"==h&&m==e}}));return!0===e.q}catch(k){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.arrayIteratorImpl=function(b){var e=0;return function(){return e<b.length?{done:!1,value:b[e++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,k){b!=Array.prototype&&b!=Object.prototype&&(b[e]=k.value)};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(b,e){this.$jscomp$symbol$id_=b;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};
$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(k||"")+"_"+e++,k)}var e=0;return b}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};
$jscomp.makeIterator=function(b){var e="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return e?e.call(b):$jscomp.arrayIterator(b)};$jscomp.owns=function(b,e){return Object.prototype.hasOwnProperty.call(b,e)};$jscomp.polyfill=function(b,e,k,h){if(e){k=$jscomp.global;b=b.split(".");for(h=0;h<b.length-1;h++){var m=b[h];m in k||(k[m]={});k=k[m]}b=b[b.length-1];h=k[b];e=e(h);e!=h&&null!=e&&$jscomp.defineProperty(k,b,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("WeakMap",function(b){function e(){if(!b||!Object.seal)return!1;try{var r=Object.seal({}),d=Object.seal({}),e=new b([[r,2],[d,3]]);if(2!=e.get(r)||3!=e.get(d))return!1;e.delete(r);e.set(d,4);return!e.has(r)&&4==e.get(d)}catch(z){return!1}}function k(){}function h(d){var b=typeof d;return"object"===b&&null!==d||"function"===b}function m(d){if(!$jscomp.owns(d,l)){var b=new k;$jscomp.defineProperty(d,l,{value:b})}}function n(d){var b=Object[d];b&&(Object[d]=function(d){if(d instanceof
k)return d;m(d);return b(d)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(e())return b;var l="$jscomp_hidden_"+Math.random();n("freeze");n("preventExtensions");n("seal");var u=0,d=function(d){this.id_=(u+=Math.random()+1).toString();if(d){d=$jscomp.makeIterator(d);for(var b;!(b=d.next()).done;)b=b.value,this.set(b[0],b[1])}};d.prototype.set=function(d,b){if(!h(d))throw Error("Invalid WeakMap key");m(d);if(!$jscomp.owns(d,l))throw Error("WeakMap key fail: "+
d);d[l][this.id_]=b;return this};d.prototype.get=function(d){return h(d)&&$jscomp.owns(d,l)?d[l][this.id_]:void 0};d.prototype.has=function(d){return h(d)&&$jscomp.owns(d,l)&&$jscomp.owns(d[l],this.id_)};d.prototype.delete=function(d){return h(d)&&$jscomp.owns(d,l)&&$jscomp.owns(d[l],this.id_)?delete d[l][this.id_]:!1};return d},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(b){function e(){if($jscomp.ASSUME_NO_NATIVE_MAP||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),e=new b($jscomp.makeIterator([[d,"s"]]));if("s"!=e.get(d)||1!=e.size||e.get({x:4})||e.set({x:4},"t")!=e||2!=e.size)return!1;var t=e.entries(),h=t.next();if(h.done||h.value[0]!=d||"s"!=h.value[1])return!1;h=t.next();return h.done||4!=h.value[0].x||"t"!=h.value[1]||!t.next().done?!1:!0}catch(z){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(e())return b;$jscomp.initSymbolIterator();var k=new WeakMap,h=function(d){this.data_={};this.head_=l();this.size=0;if(d){d=$jscomp.makeIterator(d);for(var b;!(b=d.next()).done;)b=b.value,this.set(b[0],b[1])}};h.prototype.set=function(d,b){d=0===d?0:d;var e=m(this,d);e.list||(e.list=this.data_[e.id]=[]);e.entry?e.entry.value=b:(e.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:d,
value:b},e.list.push(e.entry),this.head_.previous.next=e.entry,this.head_.previous=e.entry,this.size++);return this};h.prototype.delete=function(d){d=m(this,d);return d.entry&&d.list?(d.list.splice(d.index,1),d.list.length||delete this.data_[d.id],d.entry.previous.next=d.entry.next,d.entry.next.previous=d.entry.previous,d.entry.head=null,this.size--,!0):!1};h.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=l();this.size=0};h.prototype.has=function(d){return!!m(this,d).entry};
h.prototype.get=function(d){return(d=m(this,d).entry)&&d.value};h.prototype.entries=function(){return n(this,function(d){return[d.key,d.value]})};h.prototype.keys=function(){return n(this,function(d){return d.key})};h.prototype.values=function(){return n(this,function(d){return d.value})};h.prototype.forEach=function(d,b){for(var e=this.entries(),h;!(h=e.next()).done;)h=h.value,d.call(b,h[1],h[0],this)};h.prototype[Symbol.iterator]=h.prototype.entries;var m=function(d,b){var e=b&&typeof b;"object"==
e||"function"==e?k.has(b)?e=k.get(b):(e=""+ ++u,k.set(b,e)):e="p_"+b;var h=d.data_[e];if(h&&$jscomp.owns(d.data_,e))for(d=0;d<h.length;d++){var l=h[d];if(b!==b&&l.key!==l.key||b===l.key)return{id:e,list:h,index:d,entry:l}}return{id:e,list:h,index:-1,entry:void 0}},n=function(d,b){var e=d.head_;return $jscomp.iteratorPrototype(function(){if(e){for(;e.head!=d.head_;)e=e.previous;for(;e.next!=e.head;)return e=e.next,{done:!1,value:b(e)};e=null}return{done:!0,value:void 0}})},l=function(){var d={};return d.previous=
d.next=d.head=d},u=0;return h},"es6","es3");
(function(b,e){"object"===typeof exports&&"undefined"!==typeof module?module.exports=e():"function"===typeof define&&define.amd?define(e):b.PointerEventsPolyfill=e()})(this,function(){function b(a,c){c=c||Object.create(null);var g=document.createEvent("Event");g.initEvent(a,c.bubbles||!1,c.cancelable||!1);a=2;for(var b;a<d.length;a++)b=d[a],g[b]=c[b]||r[a];g.buttons=c.buttons||0;a=c.pressure&&g.buttons?c.pressure:g.buttons?.5:0;g.x=g.clientX;g.y=g.clientY;g.pointerId=c.pointerId||0;g.width=c.width||
0;g.height=c.height||0;g.pressure=a;g.tiltX=c.tiltX||0;g.tiltY=c.tiltY||0;g.twist=c.twist||0;g.tangentialPressure=c.tangentialPressure||0;g.pointerType=c.pointerType||"";g.hwTimestamp=c.hwTimestamp||0;g.isPrimary=c.isPrimary||!1;return g}function e(){this.array=[];this.size=0}function k(a,c,g,b){this.addCallback=a.bind(b);this.removeCallback=c.bind(b);this.changedCallback=g.bind(b);D&&(this.observer=new D(this.mutationWatcher.bind(this)))}function h(a){return"body /shadow-deep/ "+m(a)}function m(a){return'[touch-action="'+
a+'"]'}function n(a){return"{ -ms-touch-action: "+a+"; touch-action: "+a+"; }"}function l(a){if(!f.pointermap.has(a))throw a=Error("InvalidPointerId"),a.name="InvalidPointerId",a;}function u(a){for(var c=a.parentNode;c&&c!==a.ownerDocument;)c=c.parentNode;if(!c)throw a=Error("InvalidStateError"),a.name="InvalidStateError",a;}var d="bubbles cancelable view detail screenX screenY clientX clientY ctrlKey altKey shiftKey metaKey button relatedTarget pageX pageY".split(" "),r=[!1,!1,null,null,0,0,0,0,
!1,!1,!1,!1,0,null,0,0],t=window.Map&&window.Map.prototype.forEach?Map:e;e.prototype={set:function(a,c){if(void 0===c)return this.delete(a);this.has(a)||this.size++;this.array[a]=c},has:function(a){return void 0!==this.array[a]},delete:function(a){this.has(a)&&(delete this.array[a],this.size--)},get:function(a){return this.array[a]},clear:function(){this.size=this.array.length=0},forEach:function(a,c){return this.array.forEach(function(g,b){a.call(c,g,b,this)},this)}};var C="bubbles cancelable view detail screenX screenY clientX clientY ctrlKey altKey shiftKey metaKey button relatedTarget buttons pointerId width height pressure tiltX tiltY pointerType hwTimestamp isPrimary type target currentTarget which pageX pageY timeStamp".split(" "),
z=[!1,!1,null,null,0,0,0,0,!1,!1,!1,!1,0,null,0,0,0,0,0,0,0,"",0,!1,"",null,null,0,0,0,0],J={pointerover:1,pointerout:1,pointerenter:1,pointerleave:1},K="undefined"!==typeof SVGElementInstance,f={pointermap:new t,eventMap:Object.create(null),captureInfo:Object.create(null),eventSources:Object.create(null),eventSourceList:[],registerSource:function(a,c){var g=c.events;g&&(g.forEach(function(a){c[a]&&(this.eventMap[a]=c[a].bind(c))},this),this.eventSources[a]=c,this.eventSourceList.push(c))},register:function(a){for(var c=
this.eventSourceList.length,g=0,b;g<c&&(b=this.eventSourceList[g]);g++)b.register.call(b,a)},unregister:function(a){for(var c=this.eventSourceList.length,g=0,b;g<c&&(b=this.eventSourceList[g]);g++)b.unregister.call(b,a)},contains:function(a,c){try{return a.contains(c)}catch(g){return!1}},down:function(a){a.bubbles=!0;this.fireEvent("pointerdown",a)},move:function(a){a.bubbles=!0;this.fireEvent("pointermove",a)},up:function(a){a.bubbles=!0;this.fireEvent("pointerup",a)},enter:function(a){a.bubbles=
!1;this.fireEvent("pointerenter",a)},leave:function(a){a.bubbles=!1;this.fireEvent("pointerleave",a)},over:function(a){a.bubbles=!0;this.fireEvent("pointerover",a)},out:function(a){a.bubbles=!0;this.fireEvent("pointerout",a)},cancel:function(a){a.bubbles=!0;this.fireEvent("pointercancel",a)},leaveOut:function(a){this.out(a);this.propagate(a,this.leave,!1)},enterOver:function(a){this.over(a);this.propagate(a,this.enter,!0)},eventHandler:function(a){if(!a._handledByPE){var c=a.type;(c=this.eventMap&&
this.eventMap[c])&&c(a);a._handledByPE=!0}},listen:function(a,c){c.forEach(function(c){this.addEvent(a,c)},this)},unlisten:function(a,c){c.forEach(function(c){this.removeEvent(a,c)},this)},addEvent:function(a,c){a.addEventListener(c,this.boundHandler)},removeEvent:function(a,c){a.removeEventListener(c,this.boundHandler)},makeEvent:function(a,c){this.captureInfo[c.pointerId]&&(c.relatedTarget=null);a=new b(a,c);c.preventDefault&&(a.preventDefault=c.preventDefault);a._target=a._target||c.target;return a},
fireEvent:function(a,c){a=this.makeEvent(a,c);return this.dispatchEvent(a)},cloneEvent:function(a){for(var c=Object.create(null),g,b=0;b<C.length;b++)g=C[b],c[g]=a[g]||z[b],K&&("target"===g||"relatedTarget"===g)&&c[g]instanceof SVGElementInstance&&(c[g]=c[g].correspondingUseElement);a.preventDefault&&(c.preventDefault=function(){a.preventDefault()});return c},getTarget:function(a){var c=this.captureInfo[a.pointerId];if(!c)return a._target;if(a._target===c||!(a.type in J))return c},propagate:function(a,
c,g){for(var b=a.target,d=[];b!==document&&!b.contains(a.relatedTarget);)if(d.push(b),b=b.parentNode,!b)return;g&&d.reverse();d.forEach(function(b){a.target=b;c.call(this,a)},this)},setCapture:function(a,c,g){this.captureInfo[a]&&this.releaseCapture(a,g);this.captureInfo[a]=c;this.implicitRelease=this.releaseCapture.bind(this,a,g);document.addEventListener("pointerup",this.implicitRelease);document.addEventListener("pointercancel",this.implicitRelease);var d=new b("gotpointercapture");d.pointerId=
a;d._target=c;g||this.asyncDispatchEvent(d)},releaseCapture:function(a,c){var g=this.captureInfo[a];if(g){this.captureInfo[a]=void 0;document.removeEventListener("pointerup",this.implicitRelease);document.removeEventListener("pointercancel",this.implicitRelease);var d=new b("lostpointercapture");d.pointerId=a;d._target=g;c||this.asyncDispatchEvent(d)}},dispatchEvent:function(a){var c=this.getTarget(a);if(c)return c.dispatchEvent(a)},asyncDispatchEvent:function(a){requestAnimationFrame(this.dispatchEvent.bind(this,
a))}};f.boundHandler=f.eventHandler.bind(f);var v={shadow:function(a){if(a)return a.shadowRoot||a.webkitShadowRoot},canTarget:function(a){return a&&!!a.elementFromPoint},targetingShadow:function(a){a=this.shadow(a);if(this.canTarget(a))return a},olderShadow:function(a){var c=a.olderShadowRoot;!c&&(a=a.querySelector("shadow"))&&(c=a.olderShadowRoot);return c},allShadows:function(a){var c=[];for(a=this.shadow(a);a;)c.push(a),a=this.olderShadow(a);return c},searchRoot:function(a,c,b){if(a){var g=a.elementFromPoint(c,
b),d;for(d=this.targetingShadow(g);d;){if(a=d.elementFromPoint(c,b))return g=this.targetingShadow(a),this.searchRoot(g,c,b)||a;d=this.olderShadow(d)}return g}},owner:function(a){for(;a.parentNode;)a=a.parentNode;a.nodeType!==Node.DOCUMENT_NODE&&a.nodeType!==Node.DOCUMENT_FRAGMENT_NODE&&(a=document);return a},findTarget:function(a){var c=a.clientX,b=a.clientY;a=this.owner(a.target);a.elementFromPoint(c,b)||(a=document);return this.searchRoot(a,c,b)}},L=Array.prototype.forEach.call.bind(Array.prototype.forEach),
M=Array.prototype.map.call.bind(Array.prototype.map),N=Array.prototype.slice.call.bind(Array.prototype.slice),O=Array.prototype.filter.call.bind(Array.prototype.filter),D=window.MutationObserver||window.WebKitMutationObserver,P={subtree:!0,childList:!0,attributes:!0,attributeOldValue:!0,attributeFilter:["touch-action"]};k.prototype={watchSubtree:function(a){this.observer&&v.canTarget(a)&&this.observer.observe(a,P)},enableOnSubtree:function(a){this.watchSubtree(a);a===document&&"complete"!==document.readyState?
this.installOnLoad():this.installNewSubtree(a)},installNewSubtree:function(a){L(this.findElements(a),this.addElement,this)},findElements:function(a){return a.querySelectorAll?a.querySelectorAll("[touch-action]"):[]},removeElement:function(a){this.removeCallback(a)},addElement:function(a){this.addCallback(a)},elementChanged:function(a,c){this.changedCallback(a,c)},concatLists:function(a,c){return a.concat(N(c))},installOnLoad:function(){document.addEventListener("readystatechange",function(){"complete"===
document.readyState&&this.installNewSubtree(document)}.bind(this))},isElement:function(a){return a.nodeType===Node.ELEMENT_NODE},flattenMutationTree:function(a){var c=M(a,this.findElements,this);c.push(O(a,this.isElement));return c.reduce(this.concatLists,[])},mutationWatcher:function(a){a.forEach(this.mutationHandler,this)},mutationHandler:function(a){"childList"===a.type?(this.flattenMutationTree(a.addedNodes).forEach(this.addElement,this),this.flattenMutationTree(a.removedNodes).forEach(this.removeElement,
this)):"attributes"===a.type&&this.elementChanged(a.target,a.oldValue)}};var Q=["none","auto","pan-x","pan-y",{rule:"pan-x pan-y",selectors:["pan-x pan-y","pan-y pan-x"]}],x="",R=window.PointerEvent||window.MSPointerEvent,E=!window.ShadowDOMPolyfill&&document.head.createShadowRoot,p=f.pointermap,A=[1,4,2,8,16],w=!1;try{w=1===(new MouseEvent("test",{buttons:1})).buttons}catch(a){}var F={POINTER_ID:1,POINTER_TYPE:"mouse",events:["mousedown","mousemove","mouseup","mouseover","mouseout"],register:function(a){f.listen(a,
this.events)},unregister:function(a){f.unlisten(a,this.events)},lastTouches:[],isEventSimulatedFromTouch:function(a){var c=this.lastTouches,b=a.clientX;a=a.clientY;for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++){var h=Math.abs(a-f.y);if(25>=Math.abs(b-f.x)&&25>=h)return!0}},prepareEvent:function(a){var c=f.cloneEvent(a),b=c.preventDefault;c.preventDefault=function(){a.preventDefault();b()};c.pointerId=this.POINTER_ID;c.isPrimary=!0;c.pointerType=this.POINTER_TYPE;return c},prepareButtonsForMove:function(a,
c){var b=p.get(this.POINTER_ID);a.buttons=0!==c.which&&b?b.buttons:0;c.buttons=a.buttons},mousedown:function(a){if(!this.isEventSimulatedFromTouch(a)){var c=p.get(this.POINTER_ID),b=this.prepareEvent(a);w||(b.buttons=A[b.button],c&&(b.buttons|=c.buttons),a.buttons=b.buttons);p.set(this.POINTER_ID,a);c&&0!==c.buttons?f.move(b):f.down(b)}},mousemove:function(a){if(!this.isEventSimulatedFromTouch(a)){var c=this.prepareEvent(a);w||this.prepareButtonsForMove(c,a);c.button=-1;p.set(this.POINTER_ID,a);f.move(c)}},
mouseup:function(a){if(!this.isEventSimulatedFromTouch(a)){var c=p.get(this.POINTER_ID),b=this.prepareEvent(a);if(!w){var d=A[b.button];b.buttons=c?c.buttons&~d:0;a.buttons=b.buttons}p.set(this.POINTER_ID,a);b.buttons&=~A[b.button];0===b.buttons?f.up(b):f.move(b)}},mouseover:function(a){if(!this.isEventSimulatedFromTouch(a)){var c=this.prepareEvent(a);w||this.prepareButtonsForMove(c,a);c.button=-1;p.set(this.POINTER_ID,a);f.enterOver(c)}},mouseout:function(a){if(!this.isEventSimulatedFromTouch(a)){var c=
this.prepareEvent(a);w||this.prepareButtonsForMove(c,a);c.button=-1;f.leaveOut(c)}},cancel:function(a){a=this.prepareEvent(a);f.cancel(a);this.deactivateMouse()},deactivateMouse:function(){p.delete(this.POINTER_ID)}},S=f.captureInfo,T=v.findTarget.bind(v),B=v.allShadows.bind(v),q=f.pointermap,y={events:["touchstart","touchmove","touchend","touchcancel"],register:function(a){U.enableOnSubtree(a)},unregister:function(){},elementAdded:function(a){var c=a.getAttribute("touch-action"),b=this.touchActionToScrollType(c);
b&&(a._scrollType=b,f.listen(a,this.events),B(a).forEach(function(a){a._scrollType=b;f.listen(a,this.events)},this))},elementRemoved:function(a){a._scrollType=void 0;f.unlisten(a,this.events);B(a).forEach(function(a){a._scrollType=void 0;f.unlisten(a,this.events)},this)},elementChanged:function(a,c){var b=a.getAttribute("touch-action"),d=this.touchActionToScrollType(b);c=this.touchActionToScrollType(c);d&&c?(a._scrollType=d,B(a).forEach(function(a){a._scrollType=d},this)):c?this.elementRemoved(a):
d&&this.elementAdded(a)},scrollTypes:{EMITTER:"none",XSCROLLER:"pan-x",YSCROLLER:"pan-y",SCROLLER:/^(?:pan-x pan-y)|(?:pan-y pan-x)|auto$/},touchActionToScrollType:function(a){var c=this.scrollTypes;if("none"===a)return"none";if(a===c.XSCROLLER)return"X";if(a===c.YSCROLLER)return"Y";if(c.SCROLLER.exec(a))return"XY"},POINTER_TYPE:"touch",firstTouch:null,isPrimaryTouch:function(a){return this.firstTouch===a.identifier},setPrimaryTouch:function(a){if(0===q.size||1===q.size&&q.has(1))this.firstTouch=
a.identifier,this.firstXY={X:a.clientX,Y:a.clientY},this.scrolling=!1,this.cancelResetClickCount()},removePrimaryPointer:function(a){a.isPrimary&&(this.firstXY=this.firstTouch=null,this.resetClickCount())},clickCount:0,resetId:null,resetClickCount:function(){var a=function(){this.clickCount=0;this.resetId=null}.bind(this);this.resetId=setTimeout(a,200)},cancelResetClickCount:function(){this.resetId&&clearTimeout(this.resetId)},typeToButtons:function(a){var c=0;if("touchstart"===a||"touchmove"===a)c=
1;return c},touchToPointer:function(a){var c=this.currentTouchEvent,b=f.cloneEvent(a),d=b.pointerId=a.identifier+2;b.target=S[d]||T(b);b.bubbles=!0;b.cancelable=!0;b.detail=this.clickCount;b.button=0;b.buttons=this.typeToButtons(c.type);b.width=2*(a.radiusX||a.webkitRadiusX||0);b.height=2*(a.radiusY||a.webkitRadiusY||0);b.pressure=a.force||a.webkitForce||.5;b.isPrimary=this.isPrimaryTouch(a);b.pointerType=this.POINTER_TYPE;b.altKey=c.altKey;b.ctrlKey=c.ctrlKey;b.metaKey=c.metaKey;b.shiftKey=c.shiftKey;
var e=this;b.preventDefault=function(){e.scrolling=!1;e.firstXY=null;c.preventDefault()};return b},processTouches:function(a,c){var b=a.changedTouches;this.currentTouchEvent=a;a=0;for(var d;a<b.length;a++)d=b[a],c.call(this,this.touchToPointer(d))},shouldScroll:function(a){if(this.firstXY){var c=a.currentTarget._scrollType;if("none"===c)c=!1;else if("XY"===c)c=!0;else{a=a.changedTouches[0];var b="Y"===c?"X":"Y";c=Math.abs(a["client"+c]-this.firstXY[c])>=Math.abs(a["client"+b]-this.firstXY[b])}this.firstXY=
null;return c}},findTouch:function(a,c){for(var b=0,d=a.length,e;b<d&&(e=a[b]);b++)if(e.identifier===c)return!0},vacuumTouches:function(a){var c=a.touches;if(q.size>=c.length){var b=[];q.forEach(function(a,d){1===d||this.findTouch(c,d-2)||b.push(a.out)},this);b.forEach(this.cancelOut,this)}},touchstart:function(a){this.vacuumTouches(a);this.setPrimaryTouch(a.changedTouches[0]);this.dedupSynthMouse(a);this.scrolling||(this.clickCount++,this.processTouches(a,this.overDown))},overDown:function(a){q.set(a.pointerId,
{target:a.target,out:a,outTarget:a.target});f.enterOver(a);f.down(a)},touchmove:function(a){this.scrolling||(this.shouldScroll(a)?(this.scrolling=!0,this.touchcancel(a)):(a.preventDefault(),this.processTouches(a,this.moveOverOut)))},moveOverOut:function(a){var b=q.get(a.pointerId);if(b){var d=b.out,e=b.outTarget;f.move(a);d&&e!==a.target&&(d.relatedTarget=a.target,a.relatedTarget=e,d.target=e,a.target?(f.leaveOut(d),f.enterOver(a)):(a.target=e,a.relatedTarget=null,this.cancelOut(a)));b.out=a;b.outTarget=
a.target}},touchend:function(a){this.dedupSynthMouse(a);this.processTouches(a,this.upOut)},upOut:function(a){this.scrolling||(f.up(a),f.leaveOut(a));this.cleanUpPointer(a)},touchcancel:function(a){this.processTouches(a,this.cancelOut)},cancelOut:function(a){f.cancel(a);f.leaveOut(a);this.cleanUpPointer(a)},cleanUpPointer:function(a){q.delete(a.pointerId);this.removePrimaryPointer(a)},dedupSynthMouse:function(a){var b=F.lastTouches;a=a.changedTouches[0];this.isPrimaryTouch(a)&&(a={x:a.clientX,y:a.clientY},
b.push(a),b=function(a,b){b=a.indexOf(b);-1<b&&a.splice(b,1)}.bind(null,b,a),setTimeout(b,2500))}};var U=new k(y.elementAdded,y.elementRemoved,y.elementChanged,y);var G=f.pointermap,V=window.MSPointerEvent&&"number"===typeof window.MSPointerEvent.MSPOINTER_TYPE_MOUSE,W={events:"MSPointerDown MSPointerMove MSPointerUp MSPointerOut MSPointerOver MSPointerCancel MSGotPointerCapture MSLostPointerCapture".split(" "),register:function(a){f.listen(a,this.events)},unregister:function(a){f.unlisten(a,this.events)},
POINTER_TYPES:["","unavailable","touch","pen","mouse"],prepareEvent:function(a){var b=a;V&&(b=f.cloneEvent(a),b.pointerType=this.POINTER_TYPES[a.pointerType]);return b},cleanup:function(a){G.delete(a)},MSPointerDown:function(a){G.set(a.pointerId,a);a=this.prepareEvent(a);f.down(a)},MSPointerMove:function(a){a=this.prepareEvent(a);f.move(a)},MSPointerUp:function(a){var b=this.prepareEvent(a);f.up(b);this.cleanup(a.pointerId)},MSPointerOut:function(a){a=this.prepareEvent(a);f.leaveOut(a)},MSPointerOver:function(a){a=
this.prepareEvent(a);f.enterOver(a)},MSPointerCancel:function(a){var b=this.prepareEvent(a);f.cancel(b);this.cleanup(a.pointerId)},MSLostPointerCapture:function(a){a=f.makeEvent("lostpointercapture",a);f.dispatchEvent(a)},MSGotPointerCapture:function(a){a=f.makeEvent("gotpointercapture",a);f.dispatchEvent(a)}};if(window.navigator.msPointerEnabled){var H=function(a){l(a);u(this);0!==f.pointermap.get(a).buttons&&(f.setCapture(a,this,!0),this.msSetPointerCapture(a))};var I=function(a){l(a);f.releaseCapture(a,
!0);this.msReleasePointerCapture(a)}}else H=function(a){l(a);u(this);0!==f.pointermap.get(a).buttons&&f.setCapture(a,this)},I=function(a){l(a);f.releaseCapture(a)};var X=function(a){return!!f.captureInfo[a]};(function(){if(R){Q.forEach(function(a){String(a)===a?(x+=m(a)+n(a)+"\n",E&&(x+=h(a)+n(a)+"\n")):(x+=a.selectors.map(m)+n(a.rule)+"\n",E&&(x+=a.selectors.map(h)+n(a.rule)+"\n"))});var a=document.createElement("style");a.textContent=x;document.head.appendChild(a)}})();window.PointerEvent||(window.PointerEvent=
b,window.navigator.msPointerEnabled?(Object.defineProperty(window.navigator,"maxTouchPoints",{value:window.navigator.msMaxTouchPoints,enumerable:!0}),f.registerSource("ms",W)):(Object.defineProperty(window.navigator,"maxTouchPoints",{value:0,enumerable:!0}),f.registerSource("mouse",F),void 0!==window.ontouchstart&&f.registerSource("touch",y)),f.register(document));window.Element&&!Element.prototype.setPointerCapture&&Object.defineProperties(Element.prototype,{setPointerCapture:{value:H},releasePointerCapture:{value:I},
hasPointerCapture:{value:X}});return{dispatcher:f,Installer:k,PointerEvent:b,PointerMap:t,targetFinding:v}});
